baseURL = "https://infaspublications.github.io/"
languageCode = "ja-jp"
title = "INFAS PUBLICATIONS Developer Blog"
theme = "casper"
DisqusShortname = "infas-publications-developer-blog"
[params]
    description = "Blogs by web developers, Growth hackers, etc."
    cover = "images/cover.jpg"
    authorlocation = "Tokyo, Japan"
    googleAnalyticsUserID = "UA-34906528-3"
    hideHUGOSupport = false
    hjsStyle = "default"