baseURL = "https://infaspublications.github.io/"
languageCode = "ja-jp"
title = "INFAS PUBLICATIONS Developer Blog"
theme = "Casper"
[params]
    description = "Blogs by web developers, Growth hackers, etc."
    cover = "images/alesia-kazantceva-283288.jpg"
    authorlocation = "Tokyo, Japan"
    googleAnalyticsUserID = "UA-34906528-3"
    hideHUGOSupport = false
    hjsStyle = "default"